name = "ast1060-ecdsa-test"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 1024 

[kernel]
name = "ast1060-ecdsa-test"
requires = {flash = 32000, ram = 4096}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.uart_driver]
name = "drv-ast1060-uart"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
notifications = ["uart-irq"]
interrupts = {"uart.irq" = "uart-irq"}

[tasks.ecdsa_server]
name = "drv-openprot-ecdsa-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 2048

[tasks.ecdsa_test]
name = "task-ecdsa-test"
priority = 4
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 2048
task-slots = ["ecdsa_server", "uart_driver"]