name = "ast1060-starter"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 1024 

[kernel]
name = "ast1060-starter"
requires = {flash = 25000, ram = 4096}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.uart_driver]
name = "drv-ast1060-uart"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
notifications = ["uart-irq"]
interrupts = {"uart.irq" = "uart-irq"}
# task-slots = ["rcc_driver"]

[tasks.digest_server]
name = "digest-server"
priority = 2
max-sizes = {flash = 12288, ram = 8192}
start = true
stacksize = 2048
features = ["aspeed-hace"]

[tasks.helloworld]
name = "task-helloworld"
priority = 3
max-sizes = {flash = 12288, ram = 4096}
stacksize = 2048
uses = ["uart"]
start = true
task-slots = ["uart_driver", "digest_server"]
